export const ALT_ADMIN_DATA = 'ALT_ADMIN_DATA'
export const ALT_ADMIN_DASHBOARD = 'ALT_ADMIN_DASHBOARD'
export const ALT_WITHDRAWAL_REQUESTS = 'ALT_WITHDRAWAL_REQUESTS'
export const ALT_GIFTCARDS = 'ALT_GIFTCARDS'
